### ISSUE TITLE
Microsoft.DataFactory/factories/pipelines: missing properties in Copy discriminator

### ISSUE THREAD

**Issue by tfitzmac** [Azure/bicep-types-az#1048]
### Resource Type

Microsoft.DataFactory/factories/pipelines

### Api Version

2018-06-01

### Issue Type

Missing property(s)

### Other Notes

When Activity type is set to Copy, it looks like there are missing properties. For example, the Copy object should have a policy object. I have looked at the Swagger files and they seem to include the properties. Here is [ExecutionActivity](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L207) which includes Policy as one of its properties. [CopyActivity](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json#L1536) includes ExecutionActivity under "allOf"

When I view the ARM template generated by Data Factory it includes Policy:

"activities": [
   {
    "name": "Copy data1",
						"type": "Copy",
						"dependsOn": [],
						"policy": {
							"timeout": "7.00:00:00",
							"retry": 0,
							"retryIntervalInSeconds": 30,
							"secureOutput": false,
							"secureInput": false
						},
						"userProperties": [],

However, when I look at [CopyActivity](https://github.com/Azure/bicep-types-az/blob/main/generated/datafactory/microsoft.datafactory/2018-06-01/types.md#copyactivity) in the generated types, the policy object is not there.

### Confirm

- [X] I have searched this repository and have not found similar issue reports.

**Comment by jeskew** [comment]
This looks like it has the same root cause as #954, so it should be taken care of by the same fix.
