### ISSUE TITLE
Is it possible to use this library to serialize and deserialize an ARM template?

### ISSUE THREAD

**Issue by chunliu** [Azure/bicep-types-az#1079]
I am looking for a sample to serialize and deserialize an ARM template or RP resources with this library? Is it possible to do it with the library? Are there some samples about how to use this library other than the Bicep source code?

**Comment by jeskew** [comment]
That would not be possible with this library (the `Bicep.Types.Az` NuGet package) alone. If you are looking for a .NET library for parsing ARM JSON templates, [the `Azure.Deployments.Templates` package](https://www.nuget.org/packages/Azure.Deployments.Templates#readme-body-tab) is probably what you want.
