### ISSUE TITLE
Allow body-less resource types

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/bicep-types-az#128]
There are a few swagger resources with no body defined - for example:
https://github.com/Azure/bicep-types-az/blob/23e7ac5c833d77420557133abf0cf313196dc417/generated/managementgroups/log.out#L10-L21

We should generate Bicep types for these resources with just `id`, `name`, `type`& `apiVersion` defined, and continue to raise a warning.

**Comment by majastrz** [comment]
If it's allowed, why continue raising the warnings?

**Comment by anthony-c-martin** [comment]
> If it's allowed, why continue raising the warnings?

I was under the impression that it was a violation of the RPC, but to be fair, I haven't actually verified this.

**Comment by majastrz** [comment]
Appears to be listed as optional at https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md

**Comment by majastrz** [comment]
Oh, my mistake. The "properties" property is optional but the resource body is required. Raising the warning makes sense.
