### ISSUE TITLE
[Microsoft.DataFactory/factories/linkedservices]: The property "password" expected a value of type "SecretBase | null" but the provided value is of type "string"

### ISSUE THREAD

**Issue by dnovvak** [Azure/bicep-types-az#1319]
### Resource Type

Microsoft.DataFactory/factories/linkedservices

### Api Version

2018-06-01

### Issue Type

Other

### Other Notes

The reproduction code causes the following warning in VSCode:

> The property "password" expected a value of type "SecretBase | null" but the provided value is of type "string". If this is an inaccuracy in the documentation, please report it to the Bicep Team.

But as far I know there is no `SecretBase` param type in bicep:

```bicep
@description('SFTP password')
@secure()
param sftpPassword SecretBase
```

> The name "SecretBase" is not a valid type. Please specify one of the following types: "array", "bool", "int", "object", "string".

### Bicep Repro

```bicep
@description('SFTP password')
@secure()
param sftpPassword string

resource sftpServerLinkedService 'Microsoft.DataFactory/factories/linkedservices@2018-06-01' = {
  name: '${dataFactory.name}/sftp-server'
  properties: {
    type: 'Sftp'
    typeProperties: {
      authenticationType: 'Basic'
      host: sftpHost
      password: sftpPassword
      port: sftpPort
      userName: sftpUserName
    }
  }
}
```

### Confirm

- [X] I have searched this repository and have not found similar issue reports.

**Comment by anthony-c-martin** [comment]
Looks like you just need the following to pass in the password:

```bicep
resource sftpServerLinkedService 'Microsoft.DataFactory/factories/linkedservices@2018-06-01' = {
  name: '${dataFactory.name}/sftp-server'
  properties: {
    type: 'Sftp'
    typeProperties: {
      authenticationType: 'Basic'
      host: 'sftpHost'
      password: {
        type: 'SecureString'
        value: sftpPassword
      }
      port: 'sftpPort'
      userName: 'sftpUserName'
    }
  }
}
```

**Comment by dnovvak** [comment]
Oh, that's right. No warning now.
Thank you very much @anthony-c-martin
