### ISSUE TITLE
[Microsoft.Storage/storageAccounts]: SKU Property expects type "Sku" but actually needs a string

### ISSUE THREAD

**Issue by ArnoPeters** [Azure/bicep-types-az#1392]
### Resource Type

Microsoft.Storage/storageAccounts

### Api Version

2022-09-01

### Issue Type

Inaccurate property type(s)

### Other Notes

I wrote Bicep in VSCode for a simple storage account in Bicep, following the documentation on MS Learn. 
https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep

A warning was displayed: 
The property "sku" expected a value of type "Sku" but the provided value is of type "'Standard_GRS'".

The docs indicate that the sku is a string type property. 
https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep#sku

### Bicep Repro

```Bicep
param location string = resourceGroup().location

resource storageAccount 'Microsoft.Storage/storageAccounts@2022-09-01' = {
  kind: 'StorageV2'
  location: location
  name: 'randomname'
  sku: 'Standard_GRS'
}
```

### Confirm

- [X] I have searched this repository and have not found similar issue reports.

**Comment by stephaniezyen** [comment]
Hi @ArnoPeters!

So in order to specify a sku in Bicep, the code should look like this:

```bicep
param location string = resourceGroup().location

resource storageAccount 'Microsoft.Storage/storageAccounts@2022-09-01' = {
  kind: 'StorageV2'
  location: location
  name: 'randomname'
  sku: {
     name: 'Standard_GRS'
  }
}
```

Here's a reference to the storage account resource type and descriptions for each property: https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep

Let me know if changing this line fixes your problem!

**Comment by ArnoPeters** [comment]
Thanks for your reply @stephaniezyen!

You are absolutely right, and I have misread the docs. 

I will close this issue. 
Sorry for the inconvenience!
