### ISSUE TITLE
[Microsoft.Compute/virtualMachines]: The property "deleteOption" is not allowed on objects of type "NetworkInterfaceReferenceProperties"

### ISSUE THREAD

**Issue by jsrandle** [Azure/bicep-types-az#1409]
### Resource Type

Microsoft.Compute/virtualmachines

### Api Version

2022-11-01

### Issue Type

Inaccurate property type(s)

### Other Notes

Documentation shows deleteOption is a potential property for networkInterfaceReference [https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines?pivots=deployment-language-bicep#networkinterfacereference](url)

BICEP intellisense in VSCode states this is not a potential property.

### Bicep Repro
```bicep
param location string = resourceGroup().location
param vmname string
param size string = 'Standard_B8ms'
param computegallery string = 'IC_ComputeGallery'
param imagename string = 'IC-DevVM'
param adminUsername string
@secure()
param adminPassword string


resource VMImage 'Microsoft.Compute/galleries/images@2022-03-03' existing = {
  name: imagename
}


resource windowsVM 'Microsoft.Compute/virtualMachines@2020-12-01' = {
  name: vmname
  location: location
  properties: {
    hardwareProfile: {
      vmSize: size
    }
    osProfile: {
      computerName: vmname
      adminUsername: adminUsername
      adminPassword: adminPassword
    }
    storageProfile: {
      imageReference: {
        id: VMImage.id
        version: 'latest'
      }
      osDisk: {
        name: 'OS_Disk-${vmname}'
        caching: 'ReadWrite'
        createOption: 'FromImage'
      }
    }
    networkProfile: {
      networkInterfaces: [
        {
          id: 'id'
          properties:{
            primary: true
            deleteOption: 'Delete'
          }
        }
      ]
    }
    diagnosticsProfile: {
      bootDiagnostics: {
        enabled: true
      }
    }
  }
}
```

### Confirm

- [X] I have searched this repository and have not found similar issue reports.

**Comment by jeskew** [comment]
Hi @jsrandle,

The `Microsoft.Compute/virtualMachines` resource in the template is using the `2020-12-01` API version, which does not include the `deleteOption` property. The Bicep warning should clear if you use the `2022-11-01` version instead.
