### ISSUE TITLE
Microsoft.DBforPostgreSQL/flexibleServers/configurations always results in conflict error after initial deploy

### ISSUE THREAD

**Issue by Joeghanoe** [Azure/bicep-types-az#1507]
**Bicep version**
`Bicep CLI version 0.15.31`

**Describe the bug**
We are deploying a postgresql flexible server to azure that needs the PG_TRGM extension. When deployed on a greenfield deployment everything is fine, when redeployed however as we do in our deployment pipelines the extesion fails to deploy with the following error in Azure:

``` json
{
    "status": "Failed",
    "error": {
        "code": "ServerBusy",
        "message": "Server 'server-name-here-psql' is busy with another operation. Please try again later."
    }
}
```

This currently blocks us in succesfully deploying our desired state to azure.

**To Reproduce**
Deploy the following bicep resource to azure twice and the bug should appear:
``` bicep
// https://docs.microsoft.com/en-us/azure/templates/Microsoft.DBforPostgreSQL/flexibleServers?tabs=bicep
resource PostgreSQLResource 'Microsoft.DBforPostgreSQL/flexibleServers@2022-12-01' = {
  name: 'name-of-resource-psql'
  location: 'westeurope'
  sku: {
    name: 'Standard_B1s'
    tier: 'Burstable'
  }
  properties: {
    authConfig: {
      activeDirectoryAuth: 'Disabled'
      passwordAuth: 'Enabled'
    }
    dataEncryption: {
      type: 'SystemManaged'
    }
    version: '13'
    administratorLogin: 'admin'
    administratorLoginPassword: 'password'
    availabilityZone: '3'
    storage: {
      storageSizeGB: 20
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    network: {}
    highAvailability: {
      mode: 'Disabled'
    }
    maintenanceWindow: {
      customWindow: 'Disabled'
      dayOfWeek: 0
      startHour: 0
      startMinute: 0
    }
    replicationRole: 'Primary'
    replicaCapacity: 5
  }

  resource PgTrgmResourceExtension 'configurations' = {
    name: 'azure.extensions'
    properties: {
      value: 'PG_TRGM'
      source: 'user-override'
    }
  }
}
```

**Comment by simon-k** [comment]
I think I might have another workaround:

In my bicep I create the flexible server resource `server_psql_resource` and then I configure it like this.

```
resource serverConfiguration 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2021-06-01' = {
  parent: server_psql_resource
  name: 'metrics.collector_database_activity'
  properties: {
    source: 'user-override'
    value: 'ON'
  }
  //Use dependsOn as a workaround for known issue https://github.com/Azure/bicep-types-az/issues/1507
  dependsOn: [
    server_psql_resource
  ]
}
```

**Comment by simon-k** [comment]
> I think I might have another workaround:
> 
> In my bicep I create the flexible server resource `server_psql_resource` and then I configure it like this.
> 
> ```
> resource serverConfiguration 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2021-06-01' = {
>   parent: server_psql_resource
>   name: 'metrics.collector_database_activity'
>   properties: {
>     source: 'user-override'
>     value: 'ON'
>   }
>   //Use dependsOn as a workaround for known issue https://github.com/Azure/bicep-types-az/issues/1507
>   dependsOn: [
>     server_psql_resource
>   ]
> }
> ```
> 
> Without the `dependsOn` I get the "Server is busy"

OK, apparently this is not a valid workaround. I get the same "Server is busy" even with the `dependsOn`. It must have been some wierd timing issue that allowed it to run previously.

**Comment by Joeghanoe** [comment]
> > I think I might have another workaround:
> > In my bicep I create the flexible server resource `server_psql_resource` and then I configure it like this.
> > ```
> > resource serverConfiguration 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2021-06-01' = {
> >   parent: server_psql_resource
> >   name: 'metrics.collector_database_activity'
> >   properties: {
> >     source: 'user-override'
> >     value: 'ON'
> >   }
> >   //Use dependsOn as a workaround for known issue https://github.com/Azure/bicep-types-az/issues/1507
> >   dependsOn: [
> >     server_psql_resource
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without the `dependsOn` I get the "Server is busy"
> 
> OK, apparently this is not a valid workaround. I get the same "Server is busy" even with the `dependsOn`. It must have been some wierd timing issue that allowed it to run previously.

Thanks for thinking with me. I think for now we will leave the setting of any try to find some other workaround until this is fixed. Closing the issue.

**Comment by gihanw80** [comment]
I have had the same issue with a different extension,  I added a second stage after the primary deployment of the PostgreSQL flex server with a custom maintenance schedule. 

In my second stage, I enabled the POST_GIS (which was the root cause of the deployment failure ) extension and added some firewall rules.  Tested multiple times and didn't fail. Deployment failed 99% of the time If I added the extension setup and firewall rule to the main instead of running it after the main deployment.  @Joeghanoe Thanks so much for mentioning the extension, that really helped me to fix mine. Hope this helps !! 


`@description('Name of the new postgresql primary server')
param serverNamePrimary string 


var replicaServerName = '${serverNamePrimary}-replica'


@description('Allowed IPs')
param firewallRules array = [
  {
    name:'HQ'
    startIpAddress:'xx.xx.xx.xx'
    endIpAddress:'xx.xx.xx.xx'
  } 
  {
    name: 'app01'
    startIpAddress: 'xx.xx.xx.xx'
    endIpAddress: 'xx.xx.xx.xx'
  }
]


resource existingPrimaryPGSQLServer 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' existing = {
  name: serverNamePrimary
  }

  resource existingPrimaryPGSQLReplicaServer 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' existing = {
    name: replicaServerName
  }

//adding the FW rule to the primary server
resource addFireWallRule 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2023-03-01-preview' = [for rule in firewallRules:{
  name: rule.name
  parent: existingPrimaryPGSQLServer
  properties: {
    startIpAddress: rule.startIpAddress  
    endIpAddress: rule.endIpAddress
  }

}]


// installing the extension on Both primary and geo replica server

resource extensionPOSTGIS01 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-03-01-preview' = {
  name: 'azure.extensions'
  parent: existingPrimaryPGSQLServer
  properties:{
    value: 'POSTGIS'
    source: 'user-override'
  }
}

resource extensionPOSTGIS02'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-03-01-preview' = {
  name: 'azure.extensions'
  parent: existingPrimaryPGSQLReplicaServer 
  properties:{
    value: 'POSTGIS'
    source: 'user-override'
  }
}

`

**Comment by Stephan-DXRS** [comment]
Have you ever been able to fix? I'm facing the exact same issue for `POSTGIS` with and without `dependsOn`.

**Comment by gihanw80** [comment]
yes, I did, Are you using DevOps to deploy this? all I had to do was install the extension in a second stage. In the main release stage, I deployed just the server with a custom maintenance schedule and the replica server, and in the second stage, I enabled the firewall rules and PostGIS extensions. I deployed a couple and so far no failures :)

**Comment by Stephan-DXRS** [comment]
@gihanw80 No I'm deploying manually via VS Code. Firewall rules apply without issue, trying to enable the `POSTGIS` extension like this:
```
resource databasePostgis 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-03-01-preview' = {
  parent: databaseServer
  name: 'azure.extensions'
  properties: {
    source: 'user-override'
    value: 'postgis'
  }
}
```

**Comment by gihanw80** [comment]
@Stephan-DXRS 
ya, I did the same but it doesn't work. I believe when we deploy the server it takes time to spin up the resource on the Azure side.   During that time period if we deploy the extension it fails. you may try to run it like the one below after the first run so you can install the extension afterward. below code is what I use with DevOps.  

`resource existingPrimaryPGSQLServer 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' existing = {
  name: serverNamePrimary
  }

resource extensionPOSTGIS01 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-03-01-preview' = {
  name: 'azure.extensions'
  parent: existingPrimaryPGSQLServer
  properties:{
    value: 'POSTGIS'
    source: 'user-override'
  }
}`

**Comment by Joeghanoe** [comment]
> I have had the same issue with a different extension, I added a second stage after the primary deployment of the PostgreSQL flex server with a custom maintenance schedule.
> 
> In my second stage, I enabled the POST_GIS (which was the root cause of the deployment failure ) extension and added some firewall rules. Tested multiple times and didn't fail. Deployment failed 99% of the time If I added the extension setup and firewall rule to the main instead of running it after the main deployment. @Joeghanoe Thanks so much for mentioning the extension, that really helped me to fix mine. Hope this helps !!
> 
> `@description('Name of the new postgresql primary server') param serverNamePrimary string
> 
> var replicaServerName = '${serverNamePrimary}-replica'
> 
> @description('Allowed IPs') param firewallRules array = [ { name:'HQ' startIpAddress:'xx.xx.xx.xx' endIpAddress:'xx.xx.xx.xx' } { name: 'app01' startIpAddress: 'xx.xx.xx.xx' endIpAddress: 'xx.xx.xx.xx' } ]
> 
> resource existingPrimaryPGSQLServer 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' existing = { name: serverNamePrimary }
> 
> resource existingPrimaryPGSQLReplicaServer 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' existing = { name: replicaServerName }
> 
> //adding the FW rule to the primary server resource addFireWallRule 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2023-03-01-preview' = [for rule in firewallRules:{ name: rule.name parent: existingPrimaryPGSQLServer properties: { startIpAddress: rule.startIpAddress endIpAddress: rule.endIpAddress }
> 
> }]
> 
> // installing the extension on Both primary and geo replica server
> 
> resource extensionPOSTGIS01 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-03-01-preview' = { name: 'azure.extensions' parent: existingPrimaryPGSQLServer properties:{ value: 'POSTGIS' source: 'user-override' } }
> 
> resource extensionPOSTGIS02'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-03-01-preview' = { name: 'azure.extensions' parent: existingPrimaryPGSQLReplicaServer properties:{ value: 'POSTGIS' source: 'user-override' } }
> 
> `

Actually a genius solution, thanks so much. Until now we had been using a AzureCLI script for this. We'll create a "Config" deploy to rollout after the postgreSQL server has been instantiated. ;)

**Comment by Joeghanoe** [comment]
Ended up using the following solution, seems like the configurations must all be deployed one-by-one for azure to be able to deploy.

``` bicep
@batchSize(1)
// https://docs.microsoft.com/en-us/azure/templates/Microsoft.DBforPostgreSQL/flexibleServers/firewallRules?tabs=bicep
resource FirewallRulesResources 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2022-12-01' = [for rule in firewallRules: {
  name: rule.Name
  parent: PostgreSQLResource
  properties: {
    startIpAddress: rule.StartIpAddress
    endIpAddress: rule.EndIpAddress
  }
}]

// https://docs.microsoft.com/en-us/azure/templates/Microsoft.DBforPostgreSQL/flexibleServers/configurations?tabs=bicep
resource PgTrgmConfigurationResource 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-03-01-preview' = {
  name: 'azure.extensions'
  parent: PostgreSQLResource
  properties: {
    value: 'pg_trgm'
    source: 'user-override'
  }
  dependsOn: [
    FirewallRulesResources
  ]
}
```

**Comment by chriswue** [comment]
I have gone around in circles with Microsoft Support to fix the "Server Busy" error when deploying postgres configurations and the only way currently is to insert an artificial timeout via a deployment script and make your `configurations` resource dependent on that. What timeout is required varies, sometimes 1 sec works (keep in mind that deploying the deployment script itself takes time) but I've had to extend the timeout to 60sec to not fail randomly in our pipelines. This is really annoying because it adds a 1 minute delay that shouldn't be required to our pipelines.

Example wait script:

```
resource waitScript 'Microsoft.Resources/deploymentScripts@2023-08-01' = {
  name: 'waitForPostgres'
  location: resourceGroup().location
  kind: 'AzureCLI'
  properties: {
    azCliVersion: '2.53.0'
    cleanupPreference: 'OnSuccess'
    retentionInterval: 'PT1H'
    scriptContent: 'sleep 60'
  }
  dependsOn: [
    pgServer
  ]
}
```
