### ISSUE TITLE
Why was privateDNSZone Property ManagedClusterAPIServerAccessProfile custom removed

### ISSUE THREAD

**Issue by DanGiffen** [Azure/bicep-types-az#1546]
Hi guys,

https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?pivots=deployment-language-bicep

I see in the change log 2020-11-01 that ManagedClusterAPIServerAccessProfile privateDNSZone property now restricts to allowed values only 'system' and 'none', therefore a custom resource id string can longer be defined for the private zone. 

This is still currently available with az cli 2.48.1

--private-dns-zone                            : Private dns zone mode for private cluster.
        Allowed values are "system", "none" or custom private dns zone resource id. If not set,
        defaults to type system. Requires --enable-private-cluster to be used.

What are the options for defining this with the latest Bicep API?

Thanks
Dan

**Comment by DanGiffen** [comment]
Great thanks @brwilkinson. I've tweaked the CARML module I was using https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.ContainerService/managedClusters with my solution, tested and worked fine.

**Comment by stephaniezyen** [comment]
Tracking in issue linked by @brwilkinson as team has responded there.
