### ISSUE TITLE
Microsoft.Security/governanceRules - Incorrect Route - ruleId can't be empty Guid

### ISSUE THREAD

**Issue by dewolfs** [Azure/bicep-types-az#1664]
**Bicep version**
v0.18.4

**Describe the bug**
I try to deploy the resource Microsoft.Security governanceRules.

Bicep docs: https://learn.microsoft.com/en-us/azure/templates/microsoft.security/governancerules?pivots=deployment-language-bicep

When I deploy, I get the following error:

```
"details":[{"code":"InvalidParameter","message":"Incorrect Route - ruleId can't be empty Guid"}]}}
```

The configuration in Bicep for this resource does not provide this parameter called ruleId.

**To Reproduce**

I use the following bicep config:
```
resource mediumGovRule 'Microsoft.Security/governanceRules@2022-01-01-preview' = {
  name: 'testgovRule'
  properties: {
    conditionSets: [
      {
        property: '$.Metadata.Severity'
        value: 'Medium'
        operator: 'Equals'
      }
    ]
    displayName: 'Medium sec recomm'
    governanceEmailNotification: {
      disableManagerEmailNotification: false
      disableOwnerEmailNotification: false
    }
    isGracePeriod: false
    ownerSource: {
      type: 'Manually'
      value: 'hello@gmail.com'
    }
    remediationTimeframe: '30.00:00:00' // 30 days
    rulePriority: 101
    ruleType: 'Integrated' 
    sourceResourceType: 'Assessments'
  }
}
```

**Additional context**

When I look at the Azure REST API to create this resource I can see that ruleId is a required parameter.

URL REST API create method: https://learn.microsoft.com/en-us/rest/api/defenderforcloud/governance-rules/create-or-update?tabs=HTTP#uri-parameters

This ruleId is a GUID which should get auto-generated as part of the Bicep config for this resource.

**Comment by shenglol** [comment]
According to the resource provider's doc, the `ruleId` URI parameter must be a `GUID`, which is actually the `name` property of the Bicep resource, so you can fix the error by setting the `name` property to a `GUID` string. However, the resource provider should fix their error message since the value provided is not an empty GUID.

**Comment by dewolfs** [comment]
@shenglol thx for your reply.  I got this indeed fixed using the following param as name of the resource.

```
param highGovRoleGuid string = newGuid()
```
