### ISSUE TITLE
Microsoft.Web/connections: Missing kind with V2

### ISSUE THREAD

**Issue by bayees** [Azure/bicep-types-az#1671]
### Resource Type

Microsoft.Web/connections

### Api Version

2016-06-01

### Issue Type

Type is unavailable

### Other Notes

The property "kind" does not exist in the resource or type definition, although it might still be valid. If this is an inaccuracy in the documentation, please report it to the Bicep Team.

### Bicep Repro

```bicep
  resource LogicAppOffice365Connection 'Microsoft.Web/connections@2016-06-01' = {
    name: LogicAppOffice365ConnectionName
    location: Location
    properties: {
      displayName: 'Office 365 Outlook - Insight System Email User'
      statuses: [
        {
          status: 'Connected'
        }
      ]
      customParameterValues: {}
      nonSecretParameterValues: {}
      api: {
        #disable-next-line use-resource-id-functions
        id: '/subscriptions/${SubscriptionId}/providers/Microsoft.Web/locations/${Location}/managedApis/office365'
        type: 'Microsoft.Web/locations/managedApis'
        name: 'office365'

      }
    }
    tags: Tags
    kind: 'V2'
  }
```

### Confirm

- [X] I have read the troubleshooting guide and looked for duplicates.

**Comment by coolhome** [comment]
Also missing properties.parameterValueType, properties.parameterValueSet
