### ISSUE TITLE
Microsoft.MachineLearningServices/workspaces: UserAssignedIdentities not deploying, and documentation is unclear

### ISSUE THREAD

**Issue by johnpetersjr** [Azure/bicep-types-az#1703]
### Resource Type

Microsoft.MachineLearningServices/workspaces

### Api Version

2022-10-01

### Issue Type

Resource fails to deploy

### Other Notes

Trying to deploy a MachineLearningServices workspace using Bicep, and I want to assign an existing Managed Identity to it.  The [documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/2022-10-01/workspaces?pivots=deployment-language-bicep#managedserviceidentity) reads as follows:

```
The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.
```

Which isn't correct, it seems to be missing an apostrophe, but besides that point, I think I tried to set the userassignedId as it should, but I'm getting an error when this param is attempted:

```
resource machineLearningWorkspace 'Microsoft.MachineLearningServices/workspaces@2022-10-01' = {
  name: machineLearningWorkspaceName
  location: location
  tags: {
    blah: blah
  }
  sku: {
    name: 'Basic'
    tier: 'Basic'
  }
  identity: {
    type:'UserAssigned'
    userAssignedIdentities: {
        managedIdentityId: {}
      }
    }

  properties: { ...
<snip>
```

where my param is set to a fully-qualified resource ID of a managed identity:
```
param managedIdentityId = '/subscriptions/<snip>/resourceGroups/my-resource-group/identity/providers/Microsoft.ManagedIdentity/userAssignedIdentities/a_sample_ml_identity'
```

Error is:
```
{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.Resources/deployments/machine_learning_with_pe","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"LinkedInvalidPropertyId","message":"Property id 'managedIdentityId' at path '' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."}]}}
```
Not sure what I'm missing, is there a bug or maybe an example I can look at somewhere?  

### Confirm

- [X] I have read the troubleshooting guide and looked for duplicates.

**Comment by johnpetersjr** [comment]
Looks like the key variable has to be explicitly declared, per this other issue: https://github.com/Azure/bicep/issues/3125
I am good now, with my workaround.  Thanks anyways!

**Comment by stephaniezyen** [comment]
Thanks for letting us know @johnpetersjr !
