### ISSUE TITLE
Azure Communication Services BUG - InvalidLinkedDomains

### ISSUE THREAD

**Issue by gsuttie** [Azure/bicep-types-az#1737]
**Bicep version**
run `bicep --version` via the Bicep CLI, `az bicep version` via the AZ CLI or via VS code by navigating to the extensions tab and searching for Bicep

I'm using Bicep CLI version 0.19.5

**Describe the bug**
A clear and concise description of what the bug is vs what you expected to happen
When deploying Azure Communication Services Bicep code that previously worked has now stopped working. 

Using the following code
```bicep
param isProd bool = false
param communicationServiceName string = 'cs-medienstudio-dev'
param emailServiceName string = 'es-medienstudio-dev'

// Email Communication Service
resource emailService 'Microsoft.Communication/emailServices@2023-03-31' = {
  name: emailServiceName
  location: 'global'
  properties: {
    dataLocation: 'Europe'
  }
}

// Email Communication Services Domain (Azure Managed)
resource emailServiceAzureDomain 'Microsoft.Communication/emailServices/domains@2023-03-31' = if (!isProd) {
  parent: emailService
  name: 'AzureManagedDomain'
  location: 'global'
  properties: {
    domainManagement: 'AzureManaged'
    userEngagementTracking: 'Disabled'
  }
}

// SenderUsername (Azure Managed Domain)
resource senderUserNameAzureDomain 'Microsoft.Communication/emailServices/domains/senderUsernames@2023-03-31' = if (!isProd) {
  parent: emailServiceAzureDomain
  name: 'donotreply'
  properties: {
    username: 'DoNotReply'
    displayName: 'DoNotReply'
  }
}


// Link the correct domain based on the environment
var emailServiceResource = isProd ? emailServiceAzureDomain.id : emailServiceAzureDomain.id

// Communication Service
resource communcationService 'Microsoft.Communication/communicationServices@2023-03-31' = {
  name: communicationServiceName
  location: 'global'
  properties: {
    dataLocation: 'Europe'
    linkedDomains: [
      emailServiceResource
    ]
  }
}

// put this connection string into a key vault or (even better) use a Managed Identity to access Communication Service
var communicationServiceConnectionString = communcationService.listKeys().primaryConnectionString
```

**To Reproduce**
Deploy Azure Communication services using Bicep

**Additional context**
[{"code":"InvalidLinkedDomains","message":"Requested linked domains are not valid"}]}]}

**Comment by arcosl** [comment]
> 
Here is the code 

terraform {
  required_version = ">= 1.3, < 2"
  required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
}

provider "azapi" {
}


resource "azapi_resource" "email_service" {
  type     = "Microsoft.Communication/emailServices@2023-03-31"
  name     = "email-${var.communication_service_name}"
  location = "global"

  parent_id = var.resource_group_id
  body = jsonencode({
    properties = {
      dataLocation = var.data_location
    }
  })
  response_export_values = ["*"]
  tags                   = var.tags
}

resource "azapi_resource" "managed_domain" {
  type      = "Microsoft.Communication/emailServices/domains@2023-03-31"
  name      = "AzureManagedDomain"
  location  = "global"
  parent_id = azapi_resource.email_service.id
  body = jsonencode({
    properties = {
      domainManagement       = "AzureManaged"
      userEngagementTracking = "Disabled"
    }
  })
  depends_on = [
    azapi_resource.email_service,
  ]
  response_export_values = ["*"]
  tags                   = var.tags
}

resource "azapi_resource" "comunication_services" {
  type      = "Microsoft.Communication/communicationServices@2023-03-31"
  name      = var.communication_service_name
  location  = "global"
  parent_id = var.resource_group_id
  body = jsonencode({
    properties = {
      dataLocation = var.data_location
      linkedDomains = [
        azapi_resource.managed_domain.id
      ]
    }
  })
  response_export_values = ["*"]
  depends_on = [
    azapi_resource.managed_domain,
  ]
  tags = var.tags
}

**Comment by ThomasPe** [comment]
Hey everyone
Microsoft just confirmed this is a known bug that should be fixed by the end of the week.
Meanwhile it should be enough to write the "datalocation" value inside the communication service as lowercase without spaces (haven't tried it myself yet).

**Comment by Copennin** [comment]
@alex-frankel Now the fix has been deployed, can this issue be closed? 
@gsuttie can you confirm?

**Comment by AjayKumar-MSFT** [comment]
@gsuttie, Just following up, as @Copennin mentioned the fix was rolled out and we are not seeing this issue anymore.  Kindly do confirm, we can close this thread.

**Comment by gsuttie** [comment]
Yeah seems good now thanks all!
