### ISSUE TITLE
Microsoft.Network/virtualWans: different api's not available

### ISSUE THREAD

**Issue by steini44as** [Azure/bicep-types-az#1825]
### Resource Type

Microsoft.Network/virtualWans

### Api Version

2022-11-01,2023-02-01,2023-04-01

### Issue Type

Type is unavailable

### Confirm

- [X] I have read the troubleshooting guide and looked for duplicates.

**Comment by stephaniezyen** [comment]
Can you give more information on what types are unavailable? Also checked that all the APIs listed are available.

**Comment by steini44as** [comment]
At the moment of creating this issue, they weren't there. This can be closed.
