### ISSUE TITLE
Microsoft.KeyVault vaults/keys.properties.rotationPolicy.lifetimeActions: The property "type" expected a value of type "'Notify' | 'Rotate' | 'rotate' | null" but the provided value is of type "'notify'"

### ISSUE THREAD

**Issue by Woracheth** [Azure/bicep-types-az#1833]
### Resource Type

Microsoft.KeyVault vaults/keys

### Api Version

2022-07-01

### Issue Type

Property(s) missing validation for enum values

### Other Notes

The lower case 'notify' should be valid.

according to https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults/keys?pivots=deployment-language-bicep#action

also the API Spec https://github.com/Azure/azure-rest-api-specs/blob/9c26f9e87de17f46917036e97afc3edd4b9e5811/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2022-07-01/keys.json#L617

### Bicep Repro

      lifetimeActions: [
        {
          trigger: {
            timeBeforeExpiry: 'P30D'
          }
          action: {
            type: 'notify'
          }
        }
      ]

### Confirm

- [X] I have read the troubleshooting guide and looked for duplicates.

**Comment by jlichwa** [comment]
As described here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2022-07-01/keys.json#L616C27-L616C97

The enums should be compared insensitive to case. 

#please-close

**Comment by jlichwa** [comment]
#please-close
