### ISSUE TITLE
Issue deploying standard load balancer using IP address in backend pool

### ISSUE THREAD

**Issue by chja23** [Azure/bicep-types-az#1861]
**Bicep version**
az bicep version
Bicep CLI version 0.21.1 (d4acbd2a9f)

**Describe the bug**
When adding VMs to backend address pool by IP address, the deployment succeeds but the IP addresses are not in the backend address pool.

Here is an example.

```
resource lbtest01 'Microsoft.Network/loadBalancers@2023-05-01' = {
  name: 'lbtest01'
  location: 'southcentralus'
  sku: {
    name: 'Standard'
    tier: 'Regional'
  }
  properties: {
    frontendIPConfigurations: [
      {
        name: 'testapp-frontend'
        properties: {
          privateIPAddress: '192.168.1.102'
          privateIPAllocationMethod: 'Static'
          subnet: {
            id: '/subscriptions/replaced/resourceGroups/testrg01/providers/Microsoft.Network/virtualNetworks/testvn/subnets/testsn'
          }
          privateIPAddressVersion: 'IPv4'
        }
        zones: [
          '1'
          '2'
          '3'
        ]
      }
    ]

    backendAddressPools: [
      {
        name: 'testapp-pool'
        properties: {
          loadBalancerBackendAddresses: [
            {
              name: 'testvm02'
              properties: {
                ipAddress: '192.168.1.11'
                virtualNetwork: {
                  id: '/subscriptions/replaced/resourceGroups/testrg01/providers/Microsoft.Network/virtualNetworks/testvn'
                }
              }
            }
            {
              name: 'testvm01'
              properties: {
                ipAddress: '192.168.1.10'
                virtualNetwork: {
                  id: '/subscriptions/replaced/resourceGroups/testrg01/providers/Microsoft.Network/virtualNetworks/testvn'
                }
              }
            }
          ]
        }
      }
    ]
    loadBalancingRules: [
      {
        name: 'testapp-rule'
        properties: {
          frontendIPConfiguration: {
            id: resourceId('Microsoft.Network/loadBalancers/frontendIPConfigurations', 'lbtest01', 'testapp-frontend')
          }
          frontendPort: 80
          backendPort: 9801
          enableFloatingIP: false
          idleTimeoutInMinutes: 15
          protocol: 'Tcp'
          enableTcpReset: false
          loadDistribution: 'Default'
          disableOutboundSnat: false
          backendAddressPool: {
            id: resourceId('Microsoft.Network/loadBalancers/backendAddressPools', 'lbtest01', 'testapp-pool')
          }
          backendAddressPools: [
            {
              id: resourceId('Microsoft.Network/loadBalancers/backendAddressPools', 'lbtest01', 'testapp-pool')
            }
          ]
          probe: {
            id:  resourceId('Microsoft.Network/loadBalancers/probes', 'lbtest01', 'testapp-probe')
          }
        }
      }
    ]
    probes: [
      {
        name: 'testapp-probe'
        properties: {
          protocol: 'Tcp'
          port: 9801
          intervalInSeconds: 15
          numberOfProbes: 2
          probeThreshold: 1
        }
      }
    ]
    inboundNatRules: []
    outboundRules: []
    inboundNatPools: []
  }
}
```

**Comment by M-Eslam** [comment]
I am facing the same issue.

**Comment by Eslam10** [comment]
Any updates on this? 
I am facing the same issue.

**Comment by balliere** [comment]
Same problem here

**Comment by chja23** [comment]
I have found the solution.

The solution is this.

`resource lbtest01 'Microsoft.Network/loadBalancers@2023-05-01' = {
  name: 'lbtest01'
  location: 'southcentralus'
  sku: {
    name: 'Standard'
    tier: 'Regional'
  }
  properties: {
    frontendIPConfigurations: [
      {
        name: 'testapp-frontend'
        properties: {
          privateIPAddress: '192.168.1.102'
          privateIPAllocationMethod: 'Static'
          subnet: {
            id: '/subscriptions/replaced/resourceGroups/testrg01/providers/Microsoft.Network/virtualNetworks/testvn/subnets/testsn'
          }
          privateIPAddressVersion: 'IPv4'
        }
        zones: [
          '1'
          '2'
          '3'
        ]
      }
    ]
    backendAddressPools: [
      {
        name: 'testapp-pool'
        properties: {
          loadBalancerBackendAddresses: [
            {
              name: 'testvm02'
              properties: {
                ipAddress: '192.168.1.11'
                virtualNetwork: {
                  id: '/subscriptions/replaced/resourceGroups/testrg01/providers/Microsoft.Network/virtualNetworks/testvn'
                }
              }
            }
            {
              name: 'testvm01'
              properties: {
                ipAddress: '192.168.1.10'
                virtualNetwork: {
                  id: '/subscriptions/replaced/resourceGroups/testrg01/providers/Microsoft.Network/virtualNetworks/testvn'
                }
              }
            }
          ]
        }
      }
    ]
    loadBalancingRules: [
      {
        name: 'testapp-rule'
        properties: {
          frontendIPConfiguration: {
            id: resourceId('Microsoft.Network/loadBalancers/frontendIPConfigurations', 'lbtest01', 'testapp-frontend')
          }
          frontendPort: 80
          backendPort: 9801
          enableFloatingIP: false
          idleTimeoutInMinutes: 15
          protocol: 'Tcp'
          enableTcpReset: false
          loadDistribution: 'Default'
          disableOutboundSnat: false
          backendAddressPool: {
            id: resourceId('Microsoft.Network/loadBalancers/backendAddressPools', 'lbtest01', 'testapp-pool')
          }
          backendAddressPools: [
            {
              id: resourceId('Microsoft.Network/loadBalancers/backendAddressPools', 'lbtest01', 'testapp-pool')
            }
          ]
          probe: {
            id:  resourceId('Microsoft.Network/loadBalancers/probes', 'lbtest01', 'testapp-probe')
          }
        }
      }
    ]
    probes: [
      {
        name: 'testapp-probe'
        properties: {
          protocol: 'Tcp'
          port: 9801
          intervalInSeconds: 15
          numberOfProbes: 2
          probeThreshold: 1
        }
      }
    ]
    inboundNatRules: []
    outboundRules: []
    inboundNatPools: []
  }
}

resource testapppool 'Microsoft.Network/loadBalancers/backendAddressPools@2023-05-01' = {
  name: 'testapp-pool'
  parent: lbtest01
  properties: {
    loadBalancerBackendAddresses: [
      {
        name: 'testvm02'
        properties: {
          ipAddress: '192.168.1.11'
          virtualNetwork: {
            id: '/subscriptions/replaced/resourceGroups/testrg01/providers/Microsoft.Network/virtualNetworks/testvn'
          }
        }
      }
    ]
  }
}`

Now, I used modules and the modules calling the template to create the backendaddresspools were set to dependsOn the loadbalancer deployment.
