### ISSUE TITLE
Microsoft.Web/sites/functions/keys@2023-01-01: "The property "properties" does not exist in the resource  or type definition", but it is valid.

### ISSUE THREAD

**Issue by drobert-bfm** [Azure/bicep-types-az#2134]
### Resource Type

Microsoft.Web/sites/functions/keys

### Api Version

2023-01-01

### Issue Type

Missing property(s)

### Confirm

- [X] I have read the troubleshooting guide and looked for duplicates.

**Comment by stephaniezyen** [comment]
Closing as there is not enough information. Please share the exact missing properties in a new issue
