### ISSUE TITLE
Duplicate types are sometimes generated

### ISSUE THREAD

**Issue by majastrz** [Azure/bicep-types-az#260]
I was going through the types for an unrelated reason and noticed that some of the types are sometimes duplicated even though the summary is identical.

For example in the file https://github.com/Azure/bicep-types-az/blob/235fdc3343b678a8f2b1d9da60ea7af16c8f2f41/generated/web/microsoft.web/2015-08-01-preview/types.md, you can see the Dictionary<string, String> type several times in the summary:
![image](https://user-images.githubusercontent.com/22460039/121974977-7849df00-cd35-11eb-8d2b-cd4d40f91b90.png)

**Comment by anthony-c-martin** [comment]
Closed by #245
