### ISSUE TITLE
Missing Types

### ISSUE THREAD

**Issue by JFolberth** [Azure/bicep-types-az#28]
No idea and bit of a shot in the dark but was working on a PR for bicep examples referencing a quickstart [web app loganalytics]( https://github.com/Azure/azure-quickstart-templates/tree/master/201-web-app-loganalytics) and am getting errors on missing types. Specifically Microsoft.Web/sites/config@2020-06-01 and Microsoft.Web/sites/siteextensions@2020-06-01.  See the errors when compiling on bicep but noticed it is pulling the module definitions from this repo so not sure if this is the right spot or not.

**Comment by anthony-c-martin** [comment]
Thanks for reporting this! I believe it's a case of https://github.com/Azure/bicep/issues/657, but I'll keep this issue open until we have a solution.

**Comment by anthony-c-martin** [comment]
I'm going to close this issue - I've added a note for this to https://github.com/Azure/bicep/issues/784 and will track it there. Thanks for reporting this!
