### ISSUE TITLE
WriteOnly properties seem to be missing description

### ISSUE THREAD

**Issue by tfitzmac** [Azure/bicep-types-az#434]
This might be a duplicate of #203. 

I am noticing that any properties marked as WriteOnly are missing the description. You can notice it in [Machine Learning Services](https://github.com/Azure/bicep-types-az/blob/main/generated/machinelearningservices/microsoft.machinelearningservices/2020-05-01-preview/types.md#resource-microsoftmachinelearningservicesworkspacesdatastores2020-05-01-preview).

**Comment by anthony-c-martin** [comment]
Good find! I've also raised https://github.com/Azure/azure-rest-api-specs/issues/16216 as the RP resource definition is also totally messed up (lots of top-level properties that shouldn't be there).
