### ISSUE TITLE
Data property on Microsoft.KeyVault/vaults/keys defined as string but labeled with any

### ISSUE THREAD

**Issue by tfitzmac** [Azure/bicep-types-az#579]
The Microsoft.KeyVault/vaults/keys resource type has a property called "data" within the "release_policy" object. In the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/preview/2021-06-01-preview/keys.json#L634), it's defined as a string. But, it gets [generated](https://github.com/Azure/bicep-types-az/blob/main/generated/keyvault/microsoft.keyvault/2021-06-01-preview/types.md#keyreleasepolicy) as "any".

**Comment by jeskew** [comment]
[This log entry](https://github.com/Azure/bicep-types-az/blob/1937f344494cb7c38d0e22454f24edb8e1da7c54/generated/keyvault/log.out#L508) may be relevant. The Swagger definition indicates that the data property should be base64-encoded bytes, and I'm not sure which Autorest type that would be translated into. The `any` type [is used as a fallback](https://github.com/Azure/bicep-types-az/blob/1937f344494cb7c38d0e22454f24edb8e1da7c54/src/autorest.bicep/src/type-generator.ts#L396) when a field's type is not recognized.

**Comment by jlichwa** [comment]
It should be type string (it is just encoded string). 
Examples here https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-string#examples-2

**Comment by jeskew** [comment]
The Bicep autorest plugin uses Autorest's ModelerFour framework, [which applies a binary schema to base64 encoded strings](https://github.com/Azure/autorest/blob/88b689a5a1482d6c68e3c3dfc9d7422cadc056c8/packages/extensions/modelerfour/src/modeler/modelerfour.ts#L614-L621). This seems appropriate for SDK generation, where the SDK would be responsible for taking a byte buffer and converting it to the expected wire format, but is probably not exactly what we want in Bicep.

@jlichwa If a user wants to supply a policy today in a Bicep or ARM JSON file, do they need to provide a base64-encoded string? I can put together a test if you don't know.

**Comment by jackrichins** [comment]
Yes, it needs to be a base64-encoded string.
