### ISSUE TITLE
Property descriptions on 'any' objects

### ISSUE THREAD

**Issue by tfitzmac** [Azure/bicep-types-az#581]
Is it possible to retain the property description from the specification when a property is marked as "any"? Right now, they get a description of "Any object" but it might be more helpful to pass on the original description. For example, the [mainTemplate](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2021-05-01/templateSpecs.json#L754) property on **Microsoft.Resources/templateSpecs/versions** would get "The main Azure Resource Manager template content."

**Comment by jeskew** [comment]
This was fixed in https://github.com/Azure/bicep-types-az/pull/883.
