### ISSUE TITLE
Not able to see created Migration ServiceTask resource in Azure portal.

### ISSUE THREAD

**Issue by Abhishek8295864848** [Azure/bicep-types-az#628]
I have created Migration Project and Migration ServiceTask through bicep and i am able to see the Migration Project in Azure portal after creation but not able to see Migration ServiceTask after creation, but data migration is taking place for MySQL, so is there any way to see the created Migration ServiceTask in Azure Portal?

**Comment by majastrz** [comment]
We're not actively watching this repo for new issues. It'll be better to ask this question here: https://github.com/Azure/bicep/discussions
