### ISSUE TITLE
No documentation for type StringDictionaryProperties 

### ISSUE THREAD

**Issue by HVNunoM** [Azure/bicep-types-az#776]
I'm trying to create a resource of type Microsoft.Web/sites/config@2021-02-01
with the name 'appsettings'
The problem is that for properties i need to send them with the type StringDictionaryProperties.
How can i build a variable using that type? I cannot find that documentation anywhere.

**Comment by jeskew** [comment]
Hi @HVNunoM,

An `appsettings` configuration defines the key/value pairs that are passed as environment variables to your App Service application. There are some restrictions on what you can specify detailed on [the *Configure an App Service app* docs page](https://docs.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-app-settings), but as far as Bicep is concerned, the input object allows any key and does not require any specific key. 

You can see an example of how an `appsettings` `Microsoft.Web/sites/config` resource would be defined [in this appservice quickstart template](https://github.com/Azure/azure-quickstart-templates/blob/59692a371bc252c2fd77f020b49228e8f6f71e87/quickstarts/microsoft.web/web-app-with-redis-cache/main.bicep#L81-L89).
