### ISSUE TITLE
Unable to run type update action

### ISSUE THREAD

**Issue by jeskew** [Azure/bicep-types-az#817]
The `update-types` GH actions workflow is [failing with a "no space left on device" error](https://github.com/Azure/bicep-types-az/actions/runs/2340351635). The autorest pipeline used by the generator appears to create a large number of files in the user's temp directory and relies on the OS to clean them up. Cleanup won't happen in the middle of a workflow run (we use an Ubuntu-based image, and Ubuntu purges `/tmp` during boot), so we may need to manually clean up some of the generated files at various points in the generation script.

 I have also encountered rather extreme disk usage when running the type generator in WSL, since the WSL Ubuntu boot sequence does not clean up the `/tmp` directory. After running the type generator several times locally, I need to run `tmpreaper` within WSL and then optimize the underlying VHD file to reclaim space.

**Comment by jeskew** [comment]
Autorest exposes a [`clearTempData` function](https://github.com/Azure/autorest/blob/a5b47c3c214adb65d3cf2ae221c58cca5781a164/packages/apps/autorest/src/actions/clear-temp-data.ts#L9) that should help here (invokable via CLI as `autorest --clear-temp`).

**Comment by anthony-c-martin** [comment]
Great find!
