### ISSUE TITLE
Type generation skipped for 'Microsoft.Storage/storageAccounts/tableServices/tables@2019-06-01'

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/bicep-types-az#89]
https://github.com/Azure/bicep-types-az/blob/b609d7dbb043470bc9f16af5743f0454dd74124f/generated/storage/log.out#L12

Reported under https://github.com/Azure/bicep/issues/784#issuecomment-773181312

**Comment by jeskew** [comment]
This looks to have been corrected before #454. Types for `Microsoft.Storage/storageAccounts/tableServices/tables` are being generated, including in the API versions that raised the warning quoted above (`2019-06-01` and `2020-08-01-preview`).
